#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\SiteController::indexAction
  defaults:
    path: /app
    permanent: true

confirmation:
  path: /confirmation/{name}
  controller: App\Controller\ConfirmationController::confirmRegistering